# Generated by Django 2.1.2 on 2018-10-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(verbose_name='date_posted')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('answer_id', models.ForeignKey(on_delete='CASCADE', to='stackoverflowlite.Answers')),
                ('voter', models.ForeignKey(on_delete='CASCADE', to='stackoverflowlite.Users')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='question_owner',
            field=models.ForeignKey(on_delete='CASCADE', to='stackoverflowlite.Users'),
        ),
        migrations.AddField(
            model_name='answers',
            name='answer_owner',
            field=models.ForeignKey(on_delete='CASCADE', to='stackoverflowlite.Users'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(on_delete='CASCADE', to='stackoverflowlite.Questions'),
        ),
    ]
